# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.1’


 # 集成微信(完整版14.4M)
    pod ‘UMengUShare/Social/WeChat'
pod 'SVProgressHUD', '~> 2.0.3'

target 'WeiXinPayDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WeiXinPayDemo

end
